apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app-push-to-file-sidecar
  name: demo-app-push-to-file-sidecar
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: demo-app-push-to-file-sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app-push-to-file-sidecar
      annotations:
        # Secrets Provider configuration
        conjur.org/container-mode: sidecar
        conjur.org/secrets-destination: file
        conjur.org/conjur-secrets-policy-path.demo-app: data/bnl/ocp-apps
        conjur.org/conjur-secrets.demo-app: |
          - username
          - password
          - url
        conjur.org/secret-file-format.demo-app: "template"
        conjur.org/secret-file-path.demo-app: "./application.yml"
        conjur.org/secrets-refresh-interval: 20s
        conjur.org/secrets-refresh-enabled: "true"
    spec:
      serviceAccountName: demo-app-push-to-file-sidecar-sa
      containers:
        - name: demo-app-push-to-file-sidecar
          image: bnasslahsen/conjur-spring-boot-demos
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 5
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /opt/secrets/conjur/application.yml
            - name: CONJUR_DETECT_CHANGE
              value: "true"
          # Path to the file with the secrets
          volumeMounts:
            - name: conjur-secrets
              mountPath: /opt/secrets/conjur
              readOnly: true
            - name: conjur-templates
              mountPath: /conjur/templates
            - mountPath: /conjur/status
              name: conjur-status
          ports:
            - containerPort: 8080
        - image: cyberark/secrets-provider-for-k8s
          name: configurator
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - /usr/local/bin/conjur-secrets-provided.sh
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - name: podinfo
              mountPath: /conjur/podinfo
            - name: conjur-secrets
              mountPath: /conjur/secrets
            - name: conjur-templates
              mountPath: /conjur/templates
      volumes:
        - name: conjur-templates
          configMap:
            name: spring-boot-templates
        - name: conjur-secrets
          emptyDir:
            medium: Memory
        - downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
          name: podinfo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-push-to-file-sidecar
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32052
  selector:
    app: demo-app-push-to-file-sidecar