spring:
  datasource:
    username: demo-db
    password: demo-db
    url: jdbc:mysql://localhost:3306/demo-db
  jpa:
    hibernate:
      ddl-auto: update

conjur:
  refresh:
    enabled: true

springdoc:
  swagger-ui:
    use-root-path: true
    display-request-duration: true
    tagsSorter: alpha

logging:
  level:
    com.cyberark: DEBUG
    org.cyberark: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, refresh