spring:
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    use-root-path: true
    display-request-duration: true
    tagsSorter: alpha

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health, refresh


conjur:
  account: conjur
  appliance-url: https://emeadevops.secretsmgr.cyberark.cloud/api
  cert-file: /Users/Badr.NassLahsen/conjur-cloud.pem
  authn-login: host/data/bnl/ocp-apps/demo-app-api-key
  authn-api-key: 29c8nsn3dcddm313w5hcak7e5csce00ar3xj56eh1afwyga1d2v5aj
  