spring:
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    use-root-path: true
    display-request-duration: true
    tagsSorter: alpha

logging:
  level:
    com.cyberark: DEBUG
    org.cyberark: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, refresh


conjur:
  auth-api-key: xxxx