spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: test
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    use-root-path: true
    display-request-duration: true
    tags-sorter: alpha

logging:
  level:
    com.cyberark: DEBUG
    org.cyberark: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh