spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: test
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource


springdoc:
  swagger-ui:
    use-root-path: true
    display-request-duration: true
    tags-sorter: alpha

logging:
  level:
    com.cyberark: DEBUG
    org.cyberark: DEBUG

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health, refresh