spring:
  jpa:
    hibernate:
      ddl-auto: update
  
springdoc:
  swagger-ui:
    use-root-path: true
    display-request-duration: true
    tagsSorter: alpha

logging:
  level:
    org.cyberark: DEBUG

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health, refresh
  
  
