---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-mysql
type: Opaque
data:
stringData:
  conjur-map: |-
    username: data/bnl/ocp-apps/mysql-username
    password: data/bnl/ocp-apps/mysql-password
