apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app-summon-sidecar
  name: demo-app-summon-sidecar
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: demo-app-summon-sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app-summon-sidecar
    spec:
      serviceAccountName: demo-app-summon-sidecar-sa
      containers:
        - name: demo-app-summon-sidecar
          imagePullPolicy: IfNotPresent
          image: bnasslahsen/conjur-spring-boot-demos-summon
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /etc/summon
              name: summon-config
              readOnly: true
      volumes:
        - name: summon-config
          configMap:
            name: summon-config-sidecar
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-summon-sidecar
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32085
  selector:
    app: demo-app-summon-sidecar
---