---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: $APP_NAMESPACE
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: $APP_NAMESPACE
  name: demo-db-mysql-init
subjects:
  - kind: ServiceAccount
    namespace: $APP_NAMESPACE
    name: demo-db-mysql-sa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access