---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app-secrets-provider-sidecar
  name: demo-app-secrets-provider-sidecar
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: demo-app-secrets-provider-sidecar
  replicas: 1
  template:
    metadata:
      annotations:
        conjur.org/container-mode: sidecar
        conjur.org/secrets-refresh-enabled: "true"
        conjur.org/secrets-refresh-interval: 10s
      labels:
        app: demo-app-secrets-provider-sidecar
    spec:
      serviceAccountName: demo-app-secrets-provider-sidecar-sa
      containers:
        - name: demo-app-secrets-provider-sidecar
          imagePullPolicy: IfNotPresent
          image: bnasslahsen/conjur-spring-boot-demos
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_PROFILES_ACTIVE
              value: "refreshable"
        - image: cyberark/secrets-provider-for-k8s
          name: configurator
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /conjur/podinfo
              name: podinfo
          env:
            - name: K8S_SECRETS
              value: db-credentials-secrets-provider-for-k8s-sidecar
            - name: SECRETS_DESTINATION
              value: k8s_secrets
          envFrom:
            - configMapRef:
                name: conjur-connect
      volumes:
        - downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
          name: podinfo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-secrets-provider-sidecar
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32083
  selector:
    app: demo-app-secrets-provider-sidecar

