---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secrets-provider-for-k8s-sidecar
  labels:
    spring.cloud.kubernetes.secret: "true"
  annotations:
    spring.cloud.kubernetes.secret.apps: "demo-app-secrets-provider-sidecar"
type: Opaque
stringData:
  conjur-map: |-
    spring.datasource.username: data/bnl/ocp-apps/mysql-username
    spring.datasource.password: data/bnl/ocp-apps/mysql-password
    spring.datasource.url: data/bnl/ocp-apps/mysql-url