apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-java-sdk
  namespace: bnl-test-app-namespace
  labels:
    app: test-app-java-sdk
spec:
  selector:
    matchLabels:
      app: test-app-java-sdk
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app-java-sdk
    spec:
      serviceAccountName: test-app-java-sdk-sa
      containers:
        - name: test-app-java-sdk
          image: bnasslahsen/conjur-spring-boot-demos
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: secured-api-java
            - name: CONJUR_AUTHN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: conjur-authn-api-key
            - name: CONJUR_AUTHN_LOGIN
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: conjur-authn-login
            - name: CONJUR_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: conjur-account
            - name: CONJUR_APPLIANCE_URL
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: conjur-appliance-url
            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: CONJUR_SSL_CERTIFICATE
            - name: LOGGING_LEVEL_ORG_CYBERARK
              value: DEBUG
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-java-sdk
  namespace: bnl-test-app-namespace
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32094
  selector:
    app: test-app-java-sdk
---
