---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secrets-provider-for-k8s-sidecar
type: Opaque
data:
stringData:
  conjur-map: |-
    spring.datasource.username: vault1/lob1/ocp-safe/Database-MySQL-10.78.10.140-testuser/username
    spring.datasource.password: vault1/lob1/ocp-safe/Database-MySQL-10.78.10.140-testuser/password
    spring.datasource.url: vault1/lob1/ocp-safe/Database-MySQL-10.78.10.140-testuser/url