---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: $APP_NAMESPACE
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: $APP_NAMESPACE
  name: secrets-access-binding-sidecar
subjects:
  - kind: ServiceAccount
    namespace: $APP_NAMESPACE
    name: demo-app-secrets-provider-sidecar-sa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access