apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-api-key
  namespace: $APP_NAMESPACE
  labels:
    app: demo-app-api-key
spec:
  selector:
    matchLabels:
      app: demo-app-api-key
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app-api-key
    spec:
      serviceAccountName: demo-app-api-key-sa
      containers:
        - name: demo-app-api-key
          imagePullPolicy: IfNotPresent
          image: bnasslahsen/conjur-spring-boot-demos
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
          envFrom:
            - configMapRef:
                name: conjur-connect-java-api-key
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-api-key
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32094
  selector:
    app: demo-app-api-key
---
