apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-api-key
  namespace: bnl-demo-app-ns
  labels:
    app: demo-app-api-key
spec:
  selector:
    matchLabels:
      app: demo-app-api-key
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app-api-key
    spec:
      serviceAccountName: demo-app-api-key-sa
      containers:
        - name: demo-app-api-key
          image: bnasslahsen/conjur-spring-boot-demos
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: secured-api-java
            - name: CONJUR_AUTHN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-boot-credentials
                  key: conjur-authn-api-key
            - name: CONJUR_AUTHN_LOGIN
              valueFrom:
                secretKeyRef:
                  name: spring-boot-credentials
                  key: conjur-authn-login
            - name: CONJUR_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: spring-boot-credentials
                  key: conjur-account
            - name: CONJUR_APPLIANCE_URL
              valueFrom:
                secretKeyRef:
                  name: spring-boot-credentials
                  key: conjur-appliance-url
            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: spring-boot-credentials
                  key: CONJUR_SSL_CERTIFICATE
            - name: LOGGING_LEVEL_ORG_CYBERARK
              value: DEBUG
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-api-key
  namespace: bnl-demo-app-ns
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32094
  selector:
    app: demo-app-api-key
---
