apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-jwt
  namespace: bnl-demo-app-ns
  labels:
    app: demo-app-jwt
spec:
  selector:
    matchLabels:
      app: demo-app-jwt
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app-jwt
    spec:
      serviceAccountName: demo-app-jwt-sa
      containers:
        - name: demo-app-jwt
          image: bnasslahsen/conjur-spring-boot-demos
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          envFrom:
            - configMapRef:
                name: conjur-connect-spring-jwt
          volumeMounts:
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
          ports:
            - containerPort: 8080
      volumes:
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-jwt
  namespace: bnl-demo-app-ns
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32098
  selector:
    app: demo-app-jwt
---
