apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-jwt
  namespace: $APP_NAMESPACE
  labels:
    app: demo-app-jwt
spec:
  selector:
    matchLabels:
      app: demo-app-jwt
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app-jwt
    spec:
      serviceAccountName: demo-app-jwt-sa
      containers:
        - name: demo-app-jwt
          imagePullPolicy: IfNotPresent
          image: bnasslahsen/conjur-spring-boot-demos
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          envFrom:
            - configMapRef:
                name: conjur-connect-spring-jwt
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-jwt
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32098
  selector:
    app: demo-app-jwt
---
