apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db-mysql
  labels:
    app: demo-db-mysql
  namespace: $APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-db-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo-db-mysql
    spec:
      containers:
        - image: docker.io/mysql:5.7
          name: demo-db-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: demo-db
            - name: MYSQL_DATABASE
              value: demo-db
            - name: MYSQL_USER
              value: demo-db
            - name: MYSQL_PASSWORD
              value: demo-db
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command: ["mysql", "-h", "127.0.0.1", "-udemo-db", "-pdemo-db", "-e", "SELECT 1"]
            initialDelaySeconds: 20
            timeoutSeconds: 2
---
kind: Service
apiVersion: v1
metadata:
  name: demo-db-mysql
spec:
  selector:
    app: demo-db-mysql
  ports:
    - port: 3306
      targetPort: 3306