apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app-secretless
  name: demo-app-secretless
  namespace: $APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-secretless
  template:
    metadata:
      labels:
        app: demo-app-secretless
    spec:
      serviceAccountName: demo-app-secretless-sa
      containers:
        - image: bnasslahsen/conjur-spring-boot-demos
          name: demo-app-secretless
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: not-secured
            - name: DB_URL
              value: jdbc:mysql://localhost:3306/demo-db
            - name: DB_USERNAME
              value: dummy
            - name: DB_PASSWORD
              value: dummy
          ports:
            - containerPort: 8080
        - name: configurator
          image: cyberark/secretless-broker
          imagePullPolicy: IfNotPresent
          args: ["-f", "/etc/secretless/secretless.yml"]
          ports:
            - containerPort: 3306
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JWT_TOKEN_PATH
              value: /var/run/secrets/tokens/jwt
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /etc/secretless
              name: config
              readOnly: true
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
      volumes:
        - name: config
          configMap:
            name: secretless-config-mysql
            defaultMode: 420
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-secretless
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32087
  selector:
    app: demo-app-secretless
